-define(COUNTER_TABLE, moslof_counters).
-define(GAUGE_TABLE, moslof_gauges).
-define(HISTOGRAM_TABLE, moslof_histograms).
-define(WINDOWED_HISTOGRAM_TABLE, moslof_windowed_histograms).
-define(WINDOWED_HISTOGRAM_PIDS_TABLE, moslof_windowed_histogram_pids).
